services:
  spot_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spot_ros2
    volumes:
      - ./spot_driver/config/spot_ros_example.yaml:/ros_ws/src/robot.yaml
      - /tmp/.X11-unix:/tmp/.X11-unix  # Allow GUI (if using RViz)
      - ./workspace:/ros_ws/workspace  # Mount your local workspace (adjust path)
      - ./pcd_simulator:/ros_ws/src/pcd_simulator  # Mount your local workspace (adjust path)
    environment:
      - SPOT_NAME=${SPOT_NAME:-spot}
      - DISPLAY=$DISPLAY  # For GUI (if using RViz, etc.)
      # Default value, can be set via CLI with >>SPOT_NAME=spot docker compose up<<
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash && 
        source /ros_ws/install/setup.bash &&
        tail -F anything"
#        ros2 launch spot_ros2 fake_spot.launch.py"
#        ros2 launch spot_driver spot_driver.launch.py config_file:=/ros_ws/src/robot.yaml spot_name:=$${SPOT_NAME} launch_rviz:=False#      "
